data=c("good","average","bad","good","good","bad","average","good","average","bad")
f1=factor(data)
f1
f1=factor(data,levels=c("good","average","bad"),ordered=TRUE)
f1
#Array
arr=array(seq(1,10),dim=5)
arr
a1=array(seq(1,9),dim=c(3,3))
a1
a1=array(seq(2,8),dim=c(3,2))
a1
vec1=c(1:9)
vec2=c(10,11,12)
arr1=array(c(vec1,vec2),dim=c(2,3))
arr1
dim(arr1)
row_names=c("r1","r3")
column_names=c("c1","c2","c3")
mat_names=c("mat1","mat2")
arr2=array(c(vec1,vec2),dim=c(2,3,2),dimnames=list(row_names,column_names,mat_names))
arr2
arr[4]
Ar=seq(1:19)
Ar
Ar=append(Ar,21)
Ar
Ar=append(Ar,4,1)
Ar
Ar[Ar>5]
Ar[Ar>5 & Ar<10]
Ar[-7]
Ar[Ar=(Ar%%2!=0)]
Ar[Ar=(Ar%%2==0)]
