?list
employee_id=c(001,002,003,004)
employee_name=c("A","B","C","D")
numberofemployees=4
employee_list=list(employee_id,employee_name,numberofemployees)
print(employee_list)
#dataframes
?data.frame
uid=c(1,2,3,4,NA)
un=c("A","B","C","D","E")
strength=c(1000,1200,1400,1600,1800)
result=c(75,80,85,90,76)
location=c("N","S","E","W","NE")
uni_data=data.frame(uid,un,strength,result,location)
print(uni_data)
uni_data=data.frame("ID"=uid,"NAME"=un,strength,result,location)
print(uni_data)
str(uni_data)
summary(uni_data)
